workspace:
    base: /go
    path: src/github.com/prometheus/prometheus
pipeline:
  build:
    image: golang:${TAG}
    commands:
      - make promu
      - promu crossbuild
      - ln -s .build/linux-amd64/prometheus prometheus
      - ln -s .build/linux-amd64/promtool promtool
      - ls
      - ls .build/
matrix:
  TAG:
    - latest
