workspace:
    base: /go
    path: src/github.com/prometheus/prometheus
pipeline:
  build:
    image: sipian/golang-builder:1.10-base
    pull: true
    arch: [linux/amd64,linux/386]
  test:
    image: sipian/golang-builder:1.10-base
    pull: true
    test: true
matrix:
  TAG:
    - 1.10
