workspace:
    base: /go
    path: src/github.com/prometheus/prometheus
pipeline:
  test:
    image: sipian/golang-builder:1.10-base
    pull: true
    path: github.com/prometheus/prometheus
    test: false
  test:
    image: golang:${TAG}
    commands:
      - ls 
      - ls .build/
matrix:
  TAG:
    - 1.10
