workspace:
    base: /go
    path: src/github.com/prometheus/prometheus
pipeline:
  test:
    image: sipian/golang-builder:1.10-base
    import: github.com/prometheus/prometheus 
matrix:
  TAG:
    - 1.10
