workspace:
    base: /go
    path: src/github.com/prometheus/prometheus
pipeline:
  build:
    image: sipian/golang-builder:1.10-base
    pull: true
    path: github.com/prometheus/prometheus
  test:
    image: sipian/golang-builder:1.10-base
    pull: true
    path: github.com/prometheus/prometheus
    test: true
matrix:
  TAG:
    - 1.10
