workspace:
    path: src/github.com/prometheus/prometheus
pipeline:
  build:
    image: golang:${TAG}
    commands:
      - make check_license style unused test staticcheck
matrix:
  TAG:
    - 1.10
    - latest
