workspace:
    base: /go
    path: src/github.com/prometheus/prometheus
pipeline:
  test:
    image: sipian/golang-builder:1.10-base
    commands:
      - ls
      - ls .build/
  volumes:
    - /go/src/github.com/prometheus/prometheus:/app
matrix:
  TAG:
    - 1.10
