workspace:
    base: /promCI
    path: src/github.com/krasi-georgiev/prometheus
pipeline:
  build:
    image: golang
    commands:
      - go get
      - cd cmd/prometheus
      - go build
      - go test
branches: drone
