# list of architectures
# linux/amd64,linux/386,darwin/amd64,darwin/386,windows/amd64,windows/386,freebsd/amd64,freebsd/386,openbsd/amd64,openbsd/386,netbsd/amd64,netbsd/386,dragonfly/amd64,linux/armv5,linux/armv6,linux/armv7,linux/arm64,freebsd/armv6,freebsd/armv7,openbsd/armv7,netbsd/armv6,netbsd/armv7,linux/ppc64,linux/ppc64le,linux/mips64,linux/mips64le

# default arch - linux/amd64
# default goversion: 1.10
workspace:
    base: /go
    path: src/github.com/prometheus/prometheus
pipeline:
  build:
    image: sipian/golang-builder:1.10-base
    pull: true
    arch: [freebsd/amd64]
    goversion: "1.10"
  test:
    image: sipian/golang-builder:1.10-base
    pull: true
    test: true
matrix:
  TAG:
    - 1.10
