workspace:
    base: /go
    path: src/github.com/prometheus/prometheus
pipeline:
  test:
    image: sipian/golang-builder:1.10-base
    environment:
      - path=github.com/prometheus/prometheus
    commands:
      - ls
      - ls .build/
matrix:
  TAG:
    - 1.10
